Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-Name: Build firmware
+name: Build firmware
 
 on:
   workflow_dispatch:
@@ -29,9 +29,8 @@ jobs:
         git clone -b "$PADAVAN_BRANCH" "$PADAVAN_REPO"
         git -C padavan-ng checkout "$PADAVAN_COMMIT"
         
-        # Tự động tải hoặc biên dịch toolchain nếu link bị lỗi
         if ! wget -qO- "$PADAVAN_TOOLCHAIN_URL" | tar -C padavan-ng --zstd -xf -; then
-          echo "Download failed or outdated, building toolchain from source..."
+          echo "Download failed, building toolchain from source..."
           cd padavan-ng/toolchain-mipsel
           ./clean_toolchain
           ./build_toolchain
@@ -51,5 +50,41 @@ jobs:
       run: '[[ -f pre-build.sh ]] && . pre-build.sh || :'
 
     - name: Build firmware
-      run
-      
+      run: |
+        cp build.config padavan-ng/trunk/.config
+        cd padavan-ng/trunk
+        ./clear_tree.sh
+        ./build_firmware.sh
+        
+        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
+                        -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
+        [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
+        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
+
+    - name: Run custom post-build script
+      run: '[[ -f post-build.sh ]] && . post-build.sh || :'
+
+    - name: Prepare artifacts
+      run: |
+        cp "padavan-ng/trunk/images/$FW_FILE_NAME" .
+        echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
+
+    - name: Upload artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: padavan-ng_${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}_${{ env.BUILD_TIMESTAMP }}
+        retention-days: 7
+        path: |
+          ${{ env.FW_FILE_NAME }}
+          build.config
+
+    - name: Check firmware size
+      run: |
+        partitions=padavan-ng/trunk/configs/boards/$CONFIG_VENDOR/$CONFIG_FIRMWARE_PRODUCT_ID/partitions.config
+        max_fw_size="$(awk '/Firmware/ { getline; getline; sub(",", ""); print strtonum($2); }' "$partitions")"
+        fw_size="$(stat -c %s "$FW_FILE_NAME")"
+        if ((fw_size > max_fw_size)); then
+          echo "Firmware size exceeds max limit"
+          exit 1
+        fi
+        
